In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Dataset/Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
#select the 2nd and 3rd columns (0-indexed)
x = df.iloc[:, [2,3]].values #here ':' means all rows and '[2,3]' means col 2 & 3
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [6]:
#select the column 4
y = df.iloc[:, 4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [7]:
#split test and train data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.25, random_state=40)

In [9]:
print('x_train : ', x_train.shape, '  y_train : ', y_train.shape)

x_train :  (300, 2)   y_train :  (300,)


In [10]:
print('x_test : ', x_test.shape, '  y_test : ', y_test.shape)

x_test :  (100, 2)   y_test :  (100,)


In [11]:
#data standardization

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

In [14]:
x_train

array([[-0.98334377, -1.1271988 ],
       [ 1.23762906, -1.39076827],
       [ 0.75480888,  1.36206849],
       [ 1.52732117,  1.09849901],
       [-0.11426744, -0.01434989],
       [-0.40395955,  0.0442211 ],
       [ 1.3341931 , -0.95148581],
       [ 1.91357732,  0.89350053],
       [-0.69365166, -0.13149188],
       [ 0.17542467, -0.16077738],
       [-1.07990781,  0.51278906],
       [ 0.07886063,  0.0735066 ],
       [-1.8524201 , -1.33219728],
       [-0.50052359, -0.86362932],
       [-0.40395955, -0.80505833],
       [ 0.94793696, -1.0979133 ],
       [-0.30739552, -1.39076827],
       [ 0.36855274,  0.27850508],
       [-0.11426744,  0.24921958],
       [-0.7902157 , -0.62934534],
       [ 0.94793696, -1.03934231],
       [ 0.85137292, -0.62934534],
       [-0.30739552, -0.33649037],
       [-0.30739552, -0.95148581],
       [ 0.56168081,  2.00634943],
       [-1.17647184,  0.30779058],
       [-1.56272799,  0.30779058],
       [ 2.10670539,  1.09849901],
       [ 0.07886063,

In [16]:
#initialize logistic regression model and trainig the model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [17]:
#prediction
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [18]:
y_test

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1])

In [19]:
#confusion matrix

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[55, 11],
       [10, 24]])

In [23]:
#true positive : Actually True, Predicted True
tp = cm[0, [0]]
print('True Positive : ', tp)

True Positive :  [55]


In [24]:
#false positive : Actually False, Predicted True
fp = cm[0, [1]]
print('False Positive : ', fp)

False Positive :  [11]


In [26]:
#false negative : Actually True, Predicted False
fn = cm[1, [0]]
print('False Negative : ', fn)

False Negative :  [10]


In [27]:
#true negative : Actually False, Predicted False
tn = cm[1, [1]]
print('True Negative : ', tn)

True Negative :  [24]


In [28]:
#total of all values
total = (tp + fp + fn + tn)

In [29]:
#accuracy
accuracy = ((tp + tn) / total)*100 #for percent
print('Accuracy : ', accuracy)

Accuracy :  [79.]


In [30]:
#precision
precision = (tp / (tp + fp))*100 #for percent
print('Precision : ', precision)

Precision :  [83.33333333]


In [31]:
#recall
recall = (tp / (tp + fn))*100
print('Recall/Sensitivity : ', recall)

Recall/Sensitivity :  [84.61538462]


In [33]:
#specificity
specificity = (tn / (tn + fp))*100
print("Specificity : ", specificity)

Specificity :  [68.57142857]
